2018-11-03 00:17:00,470 ERROR: Exception on /reset_password_request [POST] [in c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\routes.py", line 92, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\email.py", line 18, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\email.py", line 9, in send_email
    mail.send(msg)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "c:\users\h84173\documents\install\python\python37-32\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\users\h84173\documents\install\python\python37-32\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\users\h84173\documents\install\python\python37-32\lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "c:\users\h84173\documents\install\python\python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "c:\users\h84173\documents\install\python\python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
2018-11-03 00:19:16,779 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:33]
2018-11-03 00:45:19,641 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:33]
2018-11-03 00:52:40,688 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 00:53:43,539 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:14:48,926 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:16:32,708 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:23:25,542 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:24:10,080 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:41:44,901 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:41:55,392 ERROR: Exception on /login [GET] [in c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=loginForm)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\templates\base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\templates\login.html", line 42, in block "app_content"
    {{ form.username(size=32, class=form-control) }}<br>
jinja2.exceptions.UndefinedError: 'control' is undefined
2018-11-03 01:42:48,686 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:45:54,225 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:48:00,980 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:49:22,174 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:51:03,638 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:53:52,671 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:55:41,475 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:56:45,639 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 01:57:51,895 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 02:07:44,512 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 11:52:46,688 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
